[[redirects]]
from="/*"
to="/"
status = 200

[[redirects]]
from = "/products/:id/*"
to ="/products/:id/"
status = 200

[[redirects]]
from = "/products/:id/address/*"
to ="/products/:id/address/"
status = 200