const shoes = {
    8385974993212 :{
        name :  "Leather Shoes",
        price : 13499,
        id : "8385974993212",
        link : 'https://milaneseleather3d.s3.ap-south-1.amazonaws.com/MonkStrap/scene+(17).glb',
        components : [{
            name : "Sole",
            meshName : "sole",
            textures : [{
                name : "Plain",
                id : "plain",
                color : [{name : "Brown" ,code :"#3C2A21"},
                            {name : "Black" ,code : "#2C3333"},
                        {name : "Light Brown" ,code : "#562B08"}]
            }]
        },{
            name : "Toe" ,
            meshName : "Part_1",
            textures : [{
                name : "Floral" ,
                id : "floral",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}]
            },
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ]},
            {
                name : "Vamp",
                meshName : "part_4_",
                textures : [{
                name : "Floral" ,
                id : "floral",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}]
            },
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ]
                
            },{
                name : "Quarter",
                meshName : "part_4_042",
                textures : [{
                name : "Floral" ,
                id : "floral",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}]
            },
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ],
                
                
            },{
                name : "Back Strip",
                meshName : "part_2",
                textures : [{
                name : "Floral" ,
                id : "floral",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}]
            },
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                
                ]
                
            }
        ]
    }
    ,
    8369670914364 : {
        name :  "Lopez",
        price : 13499,
        id : "8369670914364",
        link : "https://milaneseleather3d.s3.ap-south-1.amazonaws.com/yes_shoes.glb",
        components : [{
            name : "Vamp",
            meshName : "shoe_body_1",
            textures : [
                {
                name : "Alligator Skin",
                id : "alligator",
                color : [{name : "curry", code : "#865439" }, 
                        { name : "Rubiuo", code : '#6D3537'},
                        {name : "Cobio", code: "#6B4C2C"},
                        { name : "Lavendar", code : "#8E6D77"},
                        { name : "Tomorrow", code : "#4E4238"},
                        { name : "Karakul", code : "#2F3A37"},
                        { name : "Sea green", code : "#2C6853"},
                        { name : "Sky blue", code : "#4F4F69"},
                        { name : "Wood", code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "curry", code : "#865439" }, 
                        { name : "Rubiuo", code : '#6D3537'},
                        {name : "Cobio", code: "#6B4C2C"},
                        { name : "Lavendar", code : "#8E6D77"},
                        { name : "Tomorrow", code : "#4E4238"},
                        { name : "Karakul", code : "#2F3A37"},
                        { name : "Sea green", code : "#2C6853"},
                        { name : "Sky blue", code : "#4F4F69"},
                        { name : "Wood", code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "curry", code : "#865439" }, 
                        { name : "Rubiuo", code : '#6D3537'},
                        {name : "Cobio", code: "#6B4C2C"},
                        { name : "Lavendar", code : "#8E6D77"},
                        { name : "Tomorrow", code : "#4E4238"},
                        { name : "Karakul", code : "#2F3A37"},
                        { name : "Sea green", code : "#2C6853"},
                        { name : "Sky blue", code : "#4F4F69"},
                        { name : "Wood", code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "curry", code : "#865439" }, 
                        { name : "Rubiuo", code : '#6D3537'},
                        {name : "Cobio", code: "#6B4C2C"},
                        { name : "Lavendar", code : "#8E6D77"},
                        { name : "Tomorrow", code : "#4E4238"},
                        { name : "Karakul", code : "#2F3A37"},
                        { name : "Sea green", code : "#2C6853"},
                        { name : "Sky blue", code : "#4F4F69"},
                        { name : "Wood", code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ]
            
            },{
                name : "Apron",
                meshName : "TOP_SHOE001_Cube009_1",
                textures : [
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ]
            },{
                name : "Saddle",
                meshName : "Plane001",
                textures : [
                {
                name : "Alligator Skin" ,
                id : "alligator",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                 {
                name : "Moorland Grain" ,
                id : "moorlandGrain",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                    {
                name : "Quartz" ,
                id : "quartz",
                color : [{name : "blue" ,code : "#4F709C"},
                        {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                {
                    name : "Net" ,
                    id : "net",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Stoned" ,
                    id : "stoned",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Hemp" ,
                    id : "hemp",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Croco" ,
                    id : "croco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Reptile" ,
                    id : "reptile",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Leaf" ,
                    id : "leaf",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Soft Croco" ,
                    id : "softCroco",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Kite" ,
                    id : "kite",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                     {
                    name : "Gutting" ,
                    id : "gutting",
                    color : [{name : "blue" ,code : "#4F709C"},
                            {name : "curry" , code : "#865439" } , 
                        { name : "Rubiuo" , code : '#6D3537'}  ,
                        {name : "Cobio", code: "#6B4C2C"} ,
                        { name : "Lavendar" , code : "#8E6D77"},
                        { name : "Tomorrow" , code : "#4E4238"},
                        { name : "Karakul" , code : "#2F3A37"},
                        { name : "Sea green" , code : "#2C6853"},
                        { name : "Sky blue" , code : "#4F4F69"},
                        { name : "Wood" , code : "#735C4D"}
                    ]},
                ]
            }]
    }
}


module.exports = {shoes};